name: Upload Corpus to Backend

on:
  push:
    branches: [main]  # or your deployment branch
  workflow_dispatch:

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    env:
      BACKEND_URL: https://foliokit.im0o.cn
      ALLOWED_UPLOAD_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r script/requirements.txt 

    - name: Generate and Upload Corpus
      run: python script/generate_and_upload.py
